Repository openshift/cincinnati-operator, pull requests merged in 2020-04, with the labels that each got.

#10 Option to load graph data from an init container
  README.md
  deploy/crds/cincinnati.openshift.io_cincinnatis_crd.yaml
  deploy/crds/cincinnati.openshift.io_v1alpha1_cincinnati_cr.yaml
  dev/Dockerfile
  docs/graph-data-init-container.md
  pkg/apis/cincinnati/v1alpha1/cincinnati_types.go
  pkg/controller/cincinnati/cincinnati_controller.go
  pkg/controller/cincinnati/names.go
  pkg/controller/cincinnati/new.go
Labels: lgtm

#20 modules missing from vendor
  go.mod
  pkg/controller/cincinnati/cincinnati_controller_test.go
  vendor/github.com/pmezard/go-difflib/LICENSE
  vendor/github.com/pmezard/go-difflib/difflib/difflib.go
  vendor/github.com/stretchr/testify/LICENSE
  vendor/github.com/stretchr/testify/assert/assertion_format.go
  vendor/github.com/stretchr/testify/assert/assertion_format.go.tmpl
  vendor/github.com/stretchr/testify/assert/assertion_forward.go
  vendor/github.com/stretchr/testify/assert/assertion_forward.go.tmpl
  vendor/github.com/stretchr/testify/assert/assertion_order.go
  vendor/github.com/stretchr/testify/assert/assertions.go
  vendor/github.com/stretchr/testify/assert/doc.go
  vendor/github.com/stretchr/testify/assert/errors.go
  vendor/github.com/stretchr/testify/assert/forward_assertions.go
  vendor/github.com/stretchr/testify/assert/http_assertions.go
  vendor/k8s.io/apimachinery/pkg/util/rand/rand.go
  vendor/k8s.io/client-go/testing/actions.go
  vendor/k8s.io/client-go/testing/fake.go
  vendor/k8s.io/client-go/testing/fixture.go
  vendor/modules.txt
  vendor/sigs.k8s.io/controller-runtime/pkg/client/fake/client.go
  vendor/sigs.k8s.io/controller-runtime/pkg/client/fake/doc.go
  vendor/sigs.k8s.io/controller-runtime/pkg/internal/objectutil/filter.go
Labels: lgtm

#19 Adding more unit tests
  pkg/controller/cincinnati/cincinnati_controller_test.go
  pkg/controller/cincinnati/names.go
  pkg/controller/cincinnati/new.go
Labels: approved, lgtm, ok-to-test

#24 Add watches on Image and ConfigMap
  go.sum
  pkg/controller/cincinnati/cincinnati_controller.go
  pkg/controller/cincinnati/mapper.go
  pkg/controller/cincinnati/mapper_test.go
Labels: approved, lgtm, ok-to-test

#15 Use /var/lib and tarball for graph data
  deploy/crds/cincinnati.openshift.io_cincinnatis_crd.yaml
  dev/Dockerfile
  docs/graph-data-init-container.md
  pkg/apis/cincinnati/v1alpha1/cincinnati_types.go
  pkg/controller/cincinnati/new.go
Labels: approved, lgtm

#28 Remove git fields from CRD
  README.md
  deploy/crds/cincinnati.openshift.io_cincinnatis_crd.yaml
  deploy/crds/cincinnati.openshift.io_v1alpha1_cincinnati_cr.yaml
  deploy/olm-catalog/cincinnati-operator/0.0.1/cincinnati-operator.v0.0.1.clusterserviceversion.yaml
  docs/graph-data-init-container.md
  pkg/apis/cincinnati/v1alpha1/cincinnati_types.go
  pkg/controller/cincinnati/cincinnati_controller.go
  pkg/controller/cincinnati/cincinnati_controller_test.go
  pkg/controller/cincinnati/new.go
Labels: approved, lgtm
