Repository openshift/cincinnati-operator, pull requests merged in 2021-03, with the labels that each got.

#60 .gitignore: Drop auto-generated content
  .gitignore
Labels: approved, lgtm, lifecycle/rotten

#102 use registry.ci image in dockerfile
  Dockerfile
Labels: approved, lgtm

#100 OWNERS_ALIASES: Drop steveeJ
  OWNERS
Labels: approved, lgtm

#103 Bug 1939788: config/samples: Shorten name
  config/samples/updateservice.operator_v1_updateservice.yaml
Labels: approved, bugzilla/severity-medium, bugzilla/valid-bug, lgtm

#99 updates OpenShift doc links to current version 4.6
  docs/disconnected-cincinnati-operator.md
  docs/external-registry-ca.md
Labels: approved, documentation, lgtm
