Repository openshift/cincinnati-operator, pull requests merged in 2024-07, with the labels that each got.

#190 Clean up unused manifests
  bundle/manifests/leader-election-role_rbac.authorization.k8s.io_v1_role.yaml
  bundle/manifests/leader-election-rolebinding_rbac.authorization.k8s.io_v1_rolebinding.yaml
  bundle/manifests/metrics-reader_rbac.authorization.k8s.io_v1_clusterrole.yaml
  bundle/manifests/proxy-role_rbac.authorization.k8s.io_v1_clusterrole.yaml
  bundle/manifests/proxy-rolebinding_rbac.authorization.k8s.io_v1_clusterrolebinding.yaml
  bundle/manifests/update-service-operator.clusterserviceversion.yaml
  bundle/manifests/updateservice-operator-metrics-monitor_monitoring.coreos.com_v1_servicemonitor.yaml
  bundle/manifests/updateservice-operator-metrics_v1_service.yaml
  bundle/manifests/updateservice-operator_rbac.authorization.k8s.io_v1_rolebinding.yaml
  config/default/kustomization.yaml
  config/rbac/kustomization.yaml
  config/rbac/role_binding.yaml
  functests/updateservice_creation_test.go
  hack/deploy.sh
Labels: approved, lgtm

#185 OTA-1166: describe manifests
  bundle/manifests/update-service-operator.clusterserviceversion.yaml
  config/manager/manager.yaml
  config/manifests/bases/update-service-operator.clusterserviceversion.yaml
  controllers/new.go
  controllers/updateservice_controller_test.go
Labels: approved, lgtm, jira/valid-reference

#192 Document how to test a PR with cluster-bot
  README.md
Labels: approved, lgtm

#193 revert metadata helper container and route
  api/v1/updateservice_types.go
  controllers/names.go
  controllers/new.go
  controllers/updateservice_controller.go
  dev/Dockerfile
  functests/updateservice_creation_test.go
Labels: approved

#194 Fix a kustomize warning: 'bases' is deprecated
  config/default/kustomization.yaml
  config/manifests/kustomization.yaml
Labels: approved, lgtm

#196 cincinnati-operator: bump operator-sdk versions to v1.31.0-ocp
  bundle.Dockerfile
  bundle/manifests/update-service-operator.clusterserviceversion.yaml
  bundle/metadata/annotations.yaml
Labels: approved, lgtm

#198 Fix manifests of Makefile
  Makefile
  api/v1/updateservice_types.go
  bundle/manifests/update-service-operator.clusterserviceversion.yaml
  config/crd/bases/updateservice.operator.openshift.io_updateservices.yaml
Labels: approved, lgtm

#197 Update how to run the operator locally
  .gitignore
  Makefile
  README.md
  api/v1/zz_generated.deepcopy.go
  hack/boilerplate.go.txt
Labels: approved, lgtm

#200 Rerun operator-sdk generate kustomize manifests
  api/v1/updateservice_types.go
  bundle/manifests/update-service-operator.clusterserviceversion.yaml
  config/manifests/bases/update-service-operator.clusterserviceversion.yaml
Labels: approved, lgtm

#199 Update deploy in Makefile
  Makefile
  config/manager/manager.yaml
  hack/kustomize_edit_env_vars.sh
Labels: approved, lgtm

#201 Add verify-generate in Makefile
  Makefile
  bundle/manifests/update-service-operator.clusterserviceversion.yaml
Labels: approved, lgtm

#202 Add a new Make target scorecard-test
  Makefile
Labels: approved, lgtm

#203 Replace openshift-updateservice with openshift-update-service
  Makefile
  README.md
  config/default/kustomization.yaml
  config/manager/manager.yaml
  config/prometheus/monitor.yaml
  config/rbac/auth_proxy_service.yaml
  config/rbac/role_binding.yaml
  functests/utils.go
  tools/create-osus.sh
  tools/create-sub-group.sh
Labels: approved, lgtm

#204 Fix the scorecard-test target
  Makefile
Labels: approved, lgtm

#205 Bump version to 5.0.3-dev
  Makefile
  bundle/manifests/update-service-operator.clusterserviceversion.yaml
Labels: approved, lgtm
